In [1]:
import pandas as pd
from datetime import date, datetime

In [3]:
data = pd.read_csv('datasets/goodreads_library_export.csv')

In [4]:
int(data['Date Read'].count())

27

In [5]:
data['Year'] = pd.to_datetime(data['Date Read']).dt.year

In [9]:
data.head()

,Book Id,Title,Author,Author l-f,Additional Authors,ISBN,ISBN13,My Rating,Average Rating,Publisher,...,Date Added,Bookshelves,Bookshelves with positions,Exclusive Shelf,My Review,Spoiler,Private Notes,Read Count,Owned Copies,Year
0,9408584,"An Offer From a Gentleman (Bridgertons, #3)",Julia Quinn,"Quinn, Julia",NaN,"=""""","=""""",5,3.94,Avon,...,2025/02/22,NaN,NaN,read,NaN,NaN,NaN,1,0,2025.0
1,27883214,"Caraval (Caraval, #1)",Stephanie Garber,"Garber, Stephanie",NaN,"=""1250095255""","=""9781250095251""",4,3.97,Flatiron Books,...,2023/07/17,fantasy,fantasy (#10),read,NaN,NaN,NaN,1,0,2026.0
2,60581370,"The Jasad Heir (The Scorched Throne, #1)",Sara Hashem,"Hashem, Sara",NaN,"=""0316477869""","=""9780316477864""",5,4.06,Orbit Books,...,2026/01/18,NaN,NaN,read,NaN,NaN,NaN,1,0,2026.0
3,216623880,"The Jasad Crown (The Scorched Throne, #2)",Sara Hashem,"Hashem, Sara",NaN,"=""0356520420""","=""9780356520421""",5,4.39,Orbit,...,2026/02/11,NaN,NaN,read,NaN,NaN,NaN,1,0,2026.0
4,60784546,"Divine Rivals (Letters of Enchantment, #1)",Rebecca Ross,"Ross, Rebecca",NaN,"=""1250857430""","=""9781250857439""",0,4.15,Wednesday Books,...,2023/07/31,currently-reading,currently-reading (#3),currently-reading,NaN,NaN,NaN,1,0,NaN

In [10]:
data.iloc[:, list(range(16)) + [18]]

,Book Id,Title,Author,Author l-f,Additional Authors,ISBN,ISBN13,My Rating,Average Rating,Publisher,Binding,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Exclusive Shelf
0,9408584,"An Offer From a Gentleman (Bridgertons, #3)",Julia Quinn,"Quinn, Julia",NaN,"=""""","=""""",5,3.94,Avon,Paperback,390,2009.0,2001,2025/02/17,2025/02/22,read
1,27883214,"Caraval (Caraval, #1)",Stephanie Garber,"Garber, Stephanie",NaN,"=""1250095255""","=""9781250095251""",4,3.97,Flatiron Books,Hardcover,407,2017.0,2016,2026/01/24,2023/07/17,read
2,60581370,"The Jasad Heir (The Scorched Throne, #1)",Sara Hashem,"Hashem, Sara",NaN,"=""0316477869""","=""9780316477864""",5,4.06,Orbit Books,Paperback,523,2023.0,2023,2026/02/11,2026/01/18,read
3,216623880,"The Jasad Crown (The Scorched Throne, #2)",Sara Hashem,"Hashem, Sara",NaN,"=""0356520420""","=""9780356520421""",5,4.39,Orbit,Kindle Edition,681,2025.0,2025,2026/02/22,2026/02/11,read
4,60784546,"Divine Rivals (Letters of Enchantment, #1)",Rebecca Ross,"Ross, Rebecca",NaN,"=""1250857430""","=""9781250857439""",0,4.15,Wednesday Books,Hardcover,368,2023.0,2023,NaN,2023/07/31,currently-reading
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,52867387,Beach Read,Emily Henry,"Henry, Emily",NaN,"=""1984806734""","=""9781984806734""",5,3.97,Berkley,Paperback,358,2020.0,2020,NaN,2022/06/19,read
133,56732449,The Love Hypothesis,Ali Hazelwood,"Hazelwood, Ali",NaN,"=""0593336828""","=""9780593336823""",5,4.10,Berkley Books,Paperback,400,2021.0,2021,NaN,2022/06/19,read
134,2767052,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,"Collins, Suzanne",NaN,"=""0439023483""","=""9780439023481""",5,4.35,Scholastic Press,Hardcover,374,2008.0,2008,NaN,2022/06/19,read
135,11870085,The Fault in Our Stars,John Green,"Green, John",NaN,"=""""","=""""",3,4.12,Dutton Books,Hardcover,313,2012.0,2012,NaN,2022/06/19,read
136,3,Harry Potter and the Sorcerer's Stone (Harry P...,J.K. Rowling,"Rowling, J.K.",NaN,"=""0439554934""","=""9780439554930""",4,4.47,Scholastic Inc,Hardcover,309,2003.0,1997,NaN,2022/06/19,read

In [8]:
hg = data[data['Author'] == 'Suzanne Collins']
hg[['Date Read', 'Exclusive Shelf']]

      Date Read Exclusive Shelf
94   2023/06/30            read
96   2023/06/15            read
109         NaN            read
134         NaN            read