In [3]:
import pandas as pd
from datetime import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import math
from matplotlib.ticker import MultipleLocator
import datetime

In [2]:
book_session = pd.read_csv('Kindle.reading-insights-sessions_with_adjustments.csv')
book_session['start_time'] = pd.to_datetime(book_session["start_time"], format='mixed')
book_session['end_time'] = pd.to_datetime(book_session["end_time"], format='mixed')
#book_session['start_time'] = pd.to_datetime(book_session["start_time"].str.replace(r"\.\d+Z$", "Z", regex=True))
#book_session['end_time'] = pd.to_datetime(book_session["end_time"].str.replace(r"\.\d+Z$", "Z", regex=True))

In [3]:
book_session

,ASIN,end_time,personal_document_id,product_name,reading_marketplace,start_time,total_reading_milliseconds
0,Not Available,2026-02-22 09:05:07+00:00,FF1CA210F8824CDB86FFE4891611CBDB,Divine Rivals,www.amazon.ca,2026-02-22 09:05:07+00:00,NaN
1,Not Available,2026-02-22 09:05:07.900000+00:00,FF1CA210F8824CDB86FFE4891611CBDB,Divine Rivals,www.amazon.ca,2026-02-22 09:03:39.600000+00:00,88300.0
2,Not Available,2026-02-22 09:03:31.300000+00:00,0D60C9A7556B436E8E416830A370E048,Ruthless Vows,www.amazon.ca,2026-02-22 09:03:27.900000+00:00,3400.0
3,Not Available,2026-02-22 09:03:25+00:00,0D60C9A7556B436E8E416830A370E048,Ruthless Vows,www.amazon.ca,2026-02-22 09:03:25+00:00,NaN
4,Not Available,2026-02-22 09:03:25.800000+00:00,0D60C9A7556B436E8E416830A370E048,Ruthless Vows,www.amazon.ca,2026-02-22 09:02:35.300000+00:00,50500.0
...,...,...,...,...,...,...,...
594,Not Available,2025-12-27 21:39:48+00:00,6DB4151DF8904BC1A980E5D385DF1973,Sunrise on the Reaping,www.amazon.ca,2025-12-27 21:39:48+00:00,0.0
595,Not Available,2025-12-27 21:39:46.300000+00:00,6DB4151DF8904BC1A980E5D385DF1973,Sunrise on the Reaping,www.amazon.ca,2025-12-27 21:39:02.700000+00:00,43600.0
596,Not Available,2025-12-27 21:37:55+00:00,6DB4151DF8904BC1A980E5D385DF1973,Sunrise on the Reaping,www.amazon.ca,2025-12-27 21:37:49.300000+00:00,5700.0
597,Not Available,2025-12-27 21:37:43+00:00,6DB4151DF8904BC1A980E5D385DF1973,Sunrise on the Reaping,www.amazon.ca,2025-12-27 21:37:43+00:00,0.0
598,Not Available,2025-12-27 21:37:43+00:00,6DB4151DF8904BC1A980E5D385DF1973,Sunrise on the Reaping,www.amazon.ca,2025-12-27 21:36:11+00:00,92000.0

In [4]:
book_session['start_local'] = book_session['start_time'].dt.tz_convert('America/Vancouver')
book_session['end_local'] = book_session['end_time'].dt.tz_convert('America/Vancouver')

In [5]:
book_session['start_date'] = book_session['start_local'].dt.date

In [6]:
book_session.groupby('start_date')['total_reading_milliseconds'].sum().tail(10)

start_date
2026-02-13     9976100.0
2026-02-14    10649800.0
2026-02-15    21179000.0
2026-02-16    29665400.0
2026-02-17     1860500.0
2026-02-18     4035700.0
2026-02-19     4351000.0
2026-02-20     4909600.0
2026-02-21     8178300.0
2026-02-22      163000.0
Name: total_reading_milliseconds, dtype: float64

In [13]:
s = book_session[book_session['product_name'] == 'The Jasad Crown']['total_reading_milliseconds'].sum()
s/3600000

np.float64(29.06663888888889)

In [9]:
book_session[book_session['start_date'].astype(str).str.startswith('2026-02-16')]

,ASIN,end_time,personal_document_id,product_name,reading_marketplace,start_time,total_reading_milliseconds,start_local,end_local,start_date
38,Not Available,2026-02-17 08:25:46.700000+00:00,6D216F6E29B947A8804B74EC2651AF00,The Jasad Crown,www.amazon.ca,2026-02-17 07:53:08.100000+00:00,1958600.0,2026-02-16 23:53:08.100000-08:00,2026-02-17 00:25:46.700000-08:00,2026-02-16
39,Not Available,2026-02-17 07:53:06.600000+00:00,19B3E1A0C08D4F828A835CC0580C675E,The Jasad Heir,www.amazon.ca,2026-02-17 07:52:52.500000+00:00,14100.0,2026-02-16 23:52:52.500000-08:00,2026-02-16 23:53:06.600000-08:00,2026-02-16
40,Not Available,2026-02-17 07:52:50.100000+00:00,6D216F6E29B947A8804B74EC2651AF00,The Jasad Crown,www.amazon.ca,2026-02-17 07:44:07.600000+00:00,522500.0,2026-02-16 23:44:07.600000-08:00,2026-02-16 23:52:50.100000-08:00,2026-02-16
41,Not Available,2026-02-17 07:44:01+00:00,19B3E1A0C08D4F828A835CC0580C675E,The Jasad Heir,www.amazon.ca,2026-02-17 07:43:24.900000+00:00,36100.0,2026-02-16 23:43:24.900000-08:00,2026-02-16 23:44:01-08:00,2026-02-16
42,Not Available,2026-02-17 07:43:23.400000+00:00,6D216F6E29B947A8804B74EC2651AF00,The Jasad Crown,www.amazon.ca,2026-02-17 07:11:52.200000+00:00,1891200.0,2026-02-16 23:11:52.200000-08:00,2026-02-16 23:43:23.400000-08:00,2026-02-16
43,Not Available,2026-02-17 07:11:44.500000+00:00,6D216F6E29B947A8804B74EC2651AF00,The Jasad Crown,www.amazon.ca,2026-02-17 06:34:38+00:00,2226500.0,2026-02-16 22:34:38-08:00,2026-02-16 23:11:44.500000-08:00,2026-02-16
44,Not Available,2026-02-17 06:05:54.600000+00:00,6D216F6E29B947A8804B74EC2651AF00,The Jasad Crown,www.amazon.ca,2026-02-17 05:43:06+00:00,1368600.0,2026-02-16 21:43:06-08:00,2026-02-16 22:05:54.600000-08:00,2026-02-16
45,Not Available,2026-02-17 05:35:16+00:00,6D216F6E29B947A8804B74EC2651AF00,The Jasad Crown,www.amazon.ca,2026-02-17 05:04:26.700000+00:00,1849300.0,2026-02-16 21:04:26.700000-08:00,2026-02-16 21:35:16-08:00,2026-02-16
46,Not Available,2026-02-17 03:17:10+00:00,6D216F6E29B947A8804B74EC2651AF00,The Jasad Crown,www.amazon.ca,2026-02-17 02:26:24.800000+00:00,3045200.0,2026-02-16 18:26:24.800000-08:00,2026-02-16 19:17:10-08:00,2026-02-16
47,Not Available,2026-02-17 02:06:05.100000+00:00,6D216F6E29B947A8804B74EC2651AF00,The Jasad Crown,www.amazon.ca,2026-02-17 01:56:01.400000+00:00,603700.0,2026-02-16 17:56:01.400000-08:00,2026-02-16 18:06:05.100000-08:00,2026-02-16
48,Not Available,2026-02-17 01:30:59.400000+00:00,6D216F6E29B947A8804B74EC2651AF00,The Jasad Crown,www.amazon.ca,2026-02-16 23:10:12.700000+00:00,8446700.0,2026-02-16 15:10:12.700000-08:00,2026-02-16 17:30:59.400000-08:00,2026-02-16
49,Not Available,2026-02-16 22:52:02.700000+00:00,6D216F6E29B947A8804B74EC2651AF00,The Jasad Crown,www.amazon.ca,2026-02-16 22:47:27.300000+00:00,275400.0,2026-02-16 14:47:27.300000-08:00,2026-02-16 14:52:02.700000-08:00,2026-02-16
50,Not Available,2026-02-16 22:31:02.100000+00:00,6D216F6E29B947A8804B74EC2651AF00,The Jasad Crown,www.amazon.ca,2026-02-16 22:01:59.500000+00:00,1742600.0,2026-02-16 14:01:59.500000-08:00,2026-02-16 14:31:02.100000-08:00,2026-02-16
51,Not Available,2026-02-16 22:01:41.100000+00:00,19B3E1A0C08D4F828A835CC0580C675E,The Jasad Heir,www.amazon.ca,2026-02-16 22:01:24.200000+00:00,16900.0,2026-02-16 14:01:24.200000-08:00,2026-02-16 14:01:41.100000-08:00,2026-02-16
52,Not Available,2026-02-16 22:01:15.200000+00:00,6D216F6E29B947A8804B74EC2651AF00,The Jasad Crown,www.amazon.ca,2026-02-16 22:01:10.100000+00:00,5100.0,2026-02-16 14:01:10.100000-08:00,2026-02-16 14:01:15.200000-08:00,2026-02-16
53,Not Available,2026-02-16 21:32:54.700000+00:00,6D216F6E29B947A8804B74EC2651AF00,The Jasad Crown,www.amazon.ca,2026-02-16 21:30:53.500000+00:00,121200.0,2026-02-16 13:30:53.500000-08:00,2026-02-16 13:32:54.700000-08:00,2026-02-16
54,Not Available,2026-02-16 11:40:39.800000+00:00,6D216F6E29B947A8804B74EC2651AF00,The Jasad Crown,www.amazon.ca,2026-02-16 11:26:06.600000+00:00,873200.0,2026-02-16 03:26:06.600000-08:00,2026-02-16 03:40:39.800000-08:00,2026-02-16
55,Not Available,2026-02-16 09:44:38.300000+00:00,6D216F6E29B947A8804B74EC2651AF00,The Jasad Crown,www.amazon.ca,2026-02-16 08:26:49.800000+00:00,4668500.0,2026-02-16 00:26:49.800000-08:00,2026-02-16 01:44:38.300000-08:00,2026-02-16

In [8]:
book_session

,ASIN,end_time,personal_document_id,product_name,reading_marketplace,start_time,total_reading_milliseconds,start_local,end_local,start_date
0,Not Available,2026-02-22 09:05:07+00:00,FF1CA210F8824CDB86FFE4891611CBDB,Divine Rivals,www.amazon.ca,2026-02-22 09:05:07+00:00,NaN,2026-02-22 01:05:07-08:00,2026-02-22 01:05:07-08:00,2026-02-22
1,Not Available,2026-02-22 09:05:07.900000+00:00,FF1CA210F8824CDB86FFE4891611CBDB,Divine Rivals,www.amazon.ca,2026-02-22 09:03:39.600000+00:00,88300.0,2026-02-22 01:03:39.600000-08:00,2026-02-22 01:05:07.900000-08:00,2026-02-22
2,Not Available,2026-02-22 09:03:31.300000+00:00,0D60C9A7556B436E8E416830A370E048,Ruthless Vows,www.amazon.ca,2026-02-22 09:03:27.900000+00:00,3400.0,2026-02-22 01:03:27.900000-08:00,2026-02-22 01:03:31.300000-08:00,2026-02-22
3,Not Available,2026-02-22 09:03:25+00:00,0D60C9A7556B436E8E416830A370E048,Ruthless Vows,www.amazon.ca,2026-02-22 09:03:25+00:00,NaN,2026-02-22 01:03:25-08:00,2026-02-22 01:03:25-08:00,2026-02-22
4,Not Available,2026-02-22 09:03:25.800000+00:00,0D60C9A7556B436E8E416830A370E048,Ruthless Vows,www.amazon.ca,2026-02-22 09:02:35.300000+00:00,50500.0,2026-02-22 01:02:35.300000-08:00,2026-02-22 01:03:25.800000-08:00,2026-02-22
...,...,...,...,...,...,...,...,...,...,...
594,Not Available,2025-12-27 21:39:48+00:00,6DB4151DF8904BC1A980E5D385DF1973,Sunrise on the Reaping,www.amazon.ca,2025-12-27 21:39:48+00:00,0.0,2025-12-27 13:39:48-08:00,2025-12-27 13:39:48-08:00,2025-12-27
595,Not Available,2025-12-27 21:39:46.300000+00:00,6DB4151DF8904BC1A980E5D385DF1973,Sunrise on the Reaping,www.amazon.ca,2025-12-27 21:39:02.700000+00:00,43600.0,2025-12-27 13:39:02.700000-08:00,2025-12-27 13:39:46.300000-08:00,2025-12-27
596,Not Available,2025-12-27 21:37:55+00:00,6DB4151DF8904BC1A980E5D385DF1973,Sunrise on the Reaping,www.amazon.ca,2025-12-27 21:37:49.300000+00:00,5700.0,2025-12-27 13:37:49.300000-08:00,2025-12-27 13:37:55-08:00,2025-12-27
597,Not Available,2025-12-27 21:37:43+00:00,6DB4151DF8904BC1A980E5D385DF1973,Sunrise on the Reaping,www.amazon.ca,2025-12-27 21:37:43+00:00,0.0,2025-12-27 13:37:43-08:00,2025-12-27 13:37:43-08:00,2025-12-27
598,Not Available,2025-12-27 21:37:43+00:00,6DB4151DF8904BC1A980E5D385DF1973,Sunrise on the Reaping,www.amazon.ca,2025-12-27 21:36:11+00:00,92000.0,2025-12-27 13:36:11-08:00,2025-12-27 13:37:43-08:00,2025-12-27

In [28]:
book_session.dtypes

ASIN                                                     object
end_time                                    datetime64[ns, UTC]
personal_document_id                                     object
product_name                                             object
reading_marketplace                                      object
start_time                                  datetime64[ns, UTC]
total_reading_milliseconds                                int64
start_local                   datetime64[ns, America/Vancouver]
end_local                     datetime64[ns, America/Vancouver]
start_date                                               object
dtype: object

In [1]:
def read_book_insights():

    book_session = pd.read_csv('Kindle.reading-insights-sessions_with_adjustments.csv')
    book_session['start_time'] = pd.to_datetime(book_session["start_time"], format='mixed')
    book_session['end_time'] = pd.to_datetime(book_session["end_time"], format='mixed')
    book_session['start_local'] = book_session['start_time'].dt.tz_convert('America/Vancouver')
    book_session['end_local'] = book_session['end_time'].dt.tz_convert('America/Vancouver')

    book_session['start_date'] = pd.to_datetime(book_session['start_local'].dt.date)
    book_session['end_date'] = pd.to_datetime(book_session['end_local'].dt.date)
    book_session.rename(columns={'product_name' : 'book_title'}, inplace=True)

    return book_session

In [3]:
import pandas as pd

In [4]:
insights = read_book_insights()

In [7]:
insights[insights['start_date'] <= '2026-01-01']

,ASIN,end_time,personal_document_id,book_title,reading_marketplace,start_time,total_reading_milliseconds,start_local,end_local,start_date,end_date
486,Not Available,2026-01-01 11:31:56.500000+00:00,D5EFF15011854195B68281249C44311E,marked in your heart,www.amazon.ca,2026-01-01 11:30:11+00:00,105500.0,2026-01-01 03:30:11-08:00,2026-01-01 03:31:56.500000-08:00,2026-01-01,2026-01-01
487,Not Available,2026-01-01 11:25:01.600000+00:00,D5EFF15011854195B68281249C44311E,marked in your heart,www.amazon.ca,2026-01-01 10:38:44.300000+00:00,2777300.0,2026-01-01 02:38:44.300000-08:00,2026-01-01 03:25:01.600000-08:00,2026-01-01,2026-01-01
488,Not Available,2026-01-01 10:38:38.300000+00:00,54A5A9B3503F4D9B9EF712B687F7E7B1,The Hobbit (Enhanced Edition),www.amazon.ca,2026-01-01 10:38:10+00:00,28300.0,2026-01-01 02:38:10-08:00,2026-01-01 02:38:38.300000-08:00,2026-01-01,2026-01-01
489,Not Available,2026-01-01 02:34:39.500000+00:00,D5EFF15011854195B68281249C44311E,marked in your heart,www.amazon.ca,2026-01-01 02:34:30.600000+00:00,8900.0,2025-12-31 18:34:30.600000-08:00,2025-12-31 18:34:39.500000-08:00,2025-12-31,2025-12-31
490,Not Available,2025-12-31 10:36:52.200000+00:00,D5EFF15011854195B68281249C44311E,marked in your heart,www.amazon.ca,2025-12-31 10:23:52.700000+00:00,779500.0,2025-12-31 02:23:52.700000-08:00,2025-12-31 02:36:52.200000-08:00,2025-12-31,2025-12-31
...,...,...,...,...,...,...,...,...,...,...,...
594,Not Available,2025-12-27 21:39:48+00:00,6DB4151DF8904BC1A980E5D385DF1973,Sunrise on the Reaping,www.amazon.ca,2025-12-27 21:39:48+00:00,0.0,2025-12-27 13:39:48-08:00,2025-12-27 13:39:48-08:00,2025-12-27,2025-12-27
595,Not Available,2025-12-27 21:39:46.300000+00:00,6DB4151DF8904BC1A980E5D385DF1973,Sunrise on the Reaping,www.amazon.ca,2025-12-27 21:39:02.700000+00:00,43600.0,2025-12-27 13:39:02.700000-08:00,2025-12-27 13:39:46.300000-08:00,2025-12-27,2025-12-27
596,Not Available,2025-12-27 21:37:55+00:00,6DB4151DF8904BC1A980E5D385DF1973,Sunrise on the Reaping,www.amazon.ca,2025-12-27 21:37:49.300000+00:00,5700.0,2025-12-27 13:37:49.300000-08:00,2025-12-27 13:37:55-08:00,2025-12-27,2025-12-27
597,Not Available,2025-12-27 21:37:43+00:00,6DB4151DF8904BC1A980E5D385DF1973,Sunrise on the Reaping,www.amazon.ca,2025-12-27 21:37:43+00:00,0.0,2025-12-27 13:37:43-08:00,2025-12-27 13:37:43-08:00,2025-12-27,2025-12-27
598,Not Available,2025-12-27 21:37:43+00:00,6DB4151DF8904BC1A980E5D385DF1973,Sunrise on the Reaping,www.amazon.ca,2025-12-27 21:36:11+00:00,92000.0,2025-12-27 13:36:11-08:00,2025-12-27 13:37:43-08:00,2025-12-27,2025-12-27

In [1]:
def clean_book_insights():

    book_session = pd.read_csv('datasets/Kindle.reading-insights-sessions_with_adjustments.csv')
    book_session['start_time'] = pd.to_datetime(book_session["start_time"], format='mixed')
    book_session['end_time'] = pd.to_datetime(book_session["end_time"], format='mixed')
    book_session['start_local'] = book_session['start_time'].dt.tz_convert('America/Vancouver')
    book_session['end_local'] = book_session['end_time'].dt.tz_convert('America/Vancouver')

    book_session['start_date'] = pd.to_datetime(book_session['start_local'].dt.date)
    book_session['end_date'] = pd.to_datetime(book_session['end_local'].dt.date)
    book_session.rename(columns={'product_name' : 'book_title'}, inplace=True)

    return book_session

In [4]:
data = clean_book_insights()

In [5]:
data.head()

,ASIN,end_time,personal_document_id,book_title,reading_marketplace,start_time,total_reading_milliseconds,start_local,end_local,start_date,end_date
0,Not Available,2026-02-22 09:05:07+00:00,FF1CA210F8824CDB86FFE4891611CBDB,Divine Rivals,www.amazon.ca,2026-02-22 09:05:07+00:00,NaN,2026-02-22 01:05:07-08:00,2026-02-22 01:05:07-08:00,2026-02-22,2026-02-22
1,Not Available,2026-02-22 09:05:07.900000+00:00,FF1CA210F8824CDB86FFE4891611CBDB,Divine Rivals,www.amazon.ca,2026-02-22 09:03:39.600000+00:00,88300.0,2026-02-22 01:03:39.600000-08:00,2026-02-22 01:05:07.900000-08:00,2026-02-22,2026-02-22
2,Not Available,2026-02-22 09:03:31.300000+00:00,0D60C9A7556B436E8E416830A370E048,Ruthless Vows,www.amazon.ca,2026-02-22 09:03:27.900000+00:00,3400.0,2026-02-22 01:03:27.900000-08:00,2026-02-22 01:03:31.300000-08:00,2026-02-22,2026-02-22
3,Not Available,2026-02-22 09:03:25+00:00,0D60C9A7556B436E8E416830A370E048,Ruthless Vows,www.amazon.ca,2026-02-22 09:03:25+00:00,NaN,2026-02-22 01:03:25-08:00,2026-02-22 01:03:25-08:00,2026-02-22,2026-02-22
4,Not Available,2026-02-22 09:03:25.800000+00:00,0D60C9A7556B436E8E416830A370E048,Ruthless Vows,www.amazon.ca,2026-02-22 09:02:35.300000+00:00,50500.0,2026-02-22 01:02:35.300000-08:00,2026-02-22 01:03:25.800000-08:00,2026-02-22,2026-02-22

In [6]:
data['total_reading_milliseconds'].sum()

np.float64(371273700.0)

In [ ]:
371650900.0